var arrTZCountries=[
["US","미국"],
["CA","캐나다"],
["GB","영국"],
["AU","오스트레일리아"],
["DE","독일"],
["FR","프랑스"],
["DK","덴마크"],
["IT","이탈리아"],
["ES","스페인"],
["SE","스웨덴"],
["PT","포르투갈"],
["RU","러시아"],
["FI","핀란드"],
["GR","그리스"],
["TR","터키"],
["UA","우크라이나"],
["PL","폴란드"],
["JP","일본"],
["KR","대한민국"],
["CN","중국"],
["TW","대만"],
["IL","이스라엘"],
["IN","인도"],
["BR","브라질"],
["MX","멕시코"],
["AR","아르헨티나"]
];
var arrWorldclock=[
["서울","KR","Asia/Seoul",true],
["도쿄","JP","Asia/Tokyo",true],
["상하이","CN","Asia/Shanghai",true],
["우루무치","CN","Asia/Urumqi",true],
["타이페이","TW","Asia/Taipei",true],
["뉴욕","US","America/New_York",true],
["시카고, 일리노이","US","America/Chicago",false],
["덴버, 콜로라도","US","America/Denver",false],
["로스 앤젤레스, 캘리포니아","US","America/Los_Angeles",false],
["피닉스, 아리조나","US","America/Phoenix",false],
["앵커리지, 알래스카","US","America/Anchorage",false],
["아닥, 알래스카","US","America/Adak",false],
["호놀룰루, 하와이","US","Pacific/Honolulu",false],
["런던","GB","Europe/London",true],
["시드니","AU","Australia/Sydney",true],
["토론토","CA","America/Toronto",true],
["베를린","DE","Europe/Berlin",true],
["취리히","DE","Europe/Zurich",false],
["파리","FR","Europe/Paris",false],
["코펜하겐","DK","Europe/Copenhagen",false],
["로마","IT","Europe/Rome",false],
["마드리드","ES","Europe/Madrid",false],
["세 우타, 아프리카","ES","Africa/Ceuta",false],
["카나리아 제도","ES","Atlantic/Canary",false],
["스톡홀름","SE","Europe/Stockholm",false],
["리스본","PT","Europe/Lisbon",false],
["마데이라","PT","Atlantic/Madeira",false],
["아 조레스","PT","Atlantic/Azores",false],
["칼리닌그라드","RU","Europe/Kaliningrad",false],
["모스크바","RU","Europe/Moscow",true],
["익과","RU","Europe/Samara",false],
["예 카테 린 부르크","RU","Asia/Yekaterinburg",false],
["옴 스크","RU","Asia/Omsk",false],
["노보시비르스크","RU","Asia/Novosibirsk",false],
["이르쿠츠크","RU","Asia/Irkutsk",false],
["치타","RU","Asia/Chita",false],
["블라디보스톡","RU","Asia/Vladivostok",false],
["마가","RU","Asia/Magadan",false],
["페트로 파블 롭 스크 캄차 츠키","RU","Asia/Kamchatka",false],
["헬싱키","FI","Europe/Helsinki",false],
["아테네","GR","Europe/Athens",false],
["이스탄불","TR","Europe/Istanbul",false],
["키에프","UA","Europe/Kiev",false],
["바르샤바","PL","Europe/Warsaw",false],
["예루살렘","IL","Asia/Jerusalem",false],
["뉴델리","IN","Asia/Kolkata",false],
["콜카타","IN","Asia/Kolkata",false],
["노 로냐","BR","America/Noronha",false],
["상 파울로","BR","America/Sao_Paulo",false],
["리오 데 자네이로","BR","America/Sao_Paulo",false],
["마나우스","BR","America/Manaus",false],
["리우 브랑 쿠","BR","America/Rio_Branco",false],
["멕시코 시티","MX","America/Mexico_City",false],
["부에노스 아이레스","AR","America/Argentina/Buenos_Aires",false]
];
